---
framework: jest
preRun:
     command:
        - npm install
        - npm run tsc
preMerge:
  pattern:
    - __tests__/*.js
postMerge:
  pattern: 
    - __tests__/*.js
postRun:
     command:
        - node --version
version: 1.0
